# Generated by Django 2.2.1 on 2019-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosdak',
            name='feature',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kosdak',
            name='sector',
            field=models.TextField(null=True),
        ),
    ]
