# Generated by Django 2.2.1 on 2019-07-29 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_auto_20190727_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='KospiStockInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular stock across whole data', primary_key=True, serialize=False)),
                ('impirint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, choices=[('d', 'Maintenance'), ('m', 'Manufacturimg'), ('s', 'Service'), ('r', 'Retail'), ('w', 'Wholesaler')], default='d', help_text='Kospi industry by sector', max_length=1)),
                ('kospi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Kospi')),
                ('ownner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KosdakStockInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular stock across whole data', primary_key=True, serialize=False)),
                ('impirint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, choices=[('d', 'Maintenance'), ('m', 'Manufacturimg'), ('s', 'Service'), ('r', 'Retail'), ('w', 'Wholesaler')], default='d', help_text='Kosdak industry by sector', max_length=1)),
                ('kosdak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Kosdak')),
                ('ownner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
