# Generated by Django 2.2.1 on 2019-07-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_kosdakstockinstance_kospistockinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosdakstockinstance',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='kospistockinstance',
            name='sector',
        ),
        migrations.AddField(
            model_name='kosdakstockinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Maintenance'), ('h', 'Having'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='Kosdak namming', max_length=1),
        ),
        migrations.AddField(
            model_name='kospistockinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Maintenance'), ('h', 'Having'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='Kospi Ownner ', max_length=1),
        ),
    ]
