# Generated by Django 2.2.1 on 2019-07-29 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_auto_20190729_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KosdakStockInstance',
            new_name='KosdakInstance',
        ),
        migrations.RenameModel(
            old_name='KospiStockInstance',
            new_name='KospiInstance',
        ),
        migrations.AlterModelOptions(
            name='kosdakinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set kosdak as returned'),)},
        ),
        migrations.AlterModelOptions(
            name='kospiinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set kosdak as returned'),)},
        ),
    ]
