# Generated by Django 2.2.1 on 2019-08-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20190803_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kosdakinstance',
            old_name='impirint',
            new_name='imprint',
        ),
        migrations.RenameField(
            model_name='kosdakinstance',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='kospiinstance',
            old_name='impirint',
            new_name='imprint',
        ),
        migrations.RenameField(
            model_name='kospiinstance',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='kosdakinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Maintenance'), ('h', 'Having'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='Kosdak user', max_length=1),
        ),
    ]
